package actividad4.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author jeron
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumerador = new javax.swing.JTextField();
        txtCociente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDenominador = new javax.swing.JTextField();
        btmCalcular = new javax.swing.JButton();
        btmLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numerador");

        jLabel2.setText("Denominador");

        txtNumerador.addActionListener(this::txtNumeradorActionPerformed);

        jLabel3.setText("Cociente");

        btmCalcular.setText("Calcular");
        btmCalcular.addActionListener(this::btmCalcularActionPerformed);

        btmLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumerador, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtCociente)
                            .addComponent(txtDenominador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btmCalcular)
                        .addGap(38, 38, 38)
                        .addComponent(btmLimpiar)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCalcular)
                    .addComponent(btmLimpiar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtNumeradorActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btmCalcularActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {

            JOptionPane.showMessageDialog(null, "Ingresando al primer try", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            double numerador = Double.parseDouble(txtNumerador.getText());
            double denominador = Double.parseDouble(txtDenominador.getText());
            double cociente = numerador/denominador;
            txtCociente.setText(String.valueOf(cociente));
            System.out.println("Después de la divisiOn");
            JOptionPane.showMessageDialog(null, "Despues de la division", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            } 
        
        catch (ArithmeticException e) { 
              JOptionPane.showMessageDialog(null, "Division por cero", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } 
        
        finally {
            JOptionPane.showMessageDialog(null, "Division por cero", "Atencion", JOptionPane.INFORMATION_MESSAGE);
       }
        try {
            JOptionPane.showMessageDialog(null, "Ingresando al segundo try", "Atencion", JOptionPane.INFORMATION_MESSAGE);
          Object objeto = null;
          objeto.toString();
            JOptionPane.showMessageDialog(null, "Imprimiendo objeto", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } catch (ArithmeticException e) {
          JOptionPane.showMessageDialog(null, "Division por cero", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) { 
          JOptionPane.showMessageDialog(null, "Ocurrio una excepcion", "Atencion", JOptionPane.INFORMATION_MESSAGE); 
        } finally {
          JOptionPane.showMessageDialog(null, "Ingresando al segundo finally", "Atencion", JOptionPane.INFORMATION_MESSAGE);
}
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btmCalcular;
    private javax.swing.JButton btmLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCociente;
    private javax.swing.JTextField txtDenominador;
    private javax.swing.JTextField txtNumerador;
    // End of variables declaration                   
}



